int stringLength(char *string);
void stringCopy(char *source, char *destination);
void stringReverse(char *string);
int stringCharacterPosition(char *string, char character);
int charToCode(char character);
void stringUpper(char *string);
void stringLower(char *string);
int stringIsNumeric(char *string);
int stringIsAlpha(char *string);
char *stringConcat(char *string1, char *string2);
int stringStartsWith(char *string);